<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<script>
  // new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve('你好')
  //   },1000)
  // }).then(res => {
  //   console.log(res,'第一层的代码');
  //   return new Promise((resolve, reject) => {
  //     resolve(res + '111')
  //   })
  // }).then(res => {
  //   console.log(res,'第二层的代码');
  //   return new Promise((resolve) => {
  //     resolve(res + '222')
  //   })
  // }).then(res => {
  //   console.log(res,'第三层的代码');
  //   return new Promise(resolve => {
  //     resolve(res + '333')
  //   })
  // }).then(res => {
  //   console.log(res,'第四层的代码');
  // })

  //以上代码第一次简化
  // new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve('你好')
  //   },1000)
  // }).then(res => {
  //   console.log(res,'第一层的代码');
  //   return Promise.resolve(res + '111')
  // }).then(res => {
  //   console.log(res,'第二层的代码');
  //   return Promise.resolve(res + '222')
  // }).then(res => {
  //   console.log(res,'第三层的代码');
  //   return Promise.resolve(res + '333')
  // }).then(res => {
  //   console.log(res,'第四层的代码');
  // })

  // 第三次简化:省略掉Promise.resolve
  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('你好')
    },1000)
  }).then(res => {
    console.log(res,'第一层的代码');
    return res + '111'

  }).then(res => {
    console.log(res,'第二层的代码');
    return new Promise((resolve, reject) => {
      throw 'err message'
    })

  }).then(res => {
    console.log(res,'第三层的代码');
    return res + '333'
  }).then(res => {
    console.log(res,'第四层的代码');
  }).catch(err => {
    console.log(err);
  })
</script>

</body>
</html>